const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const root = path.join(__dirname, '..');
const dist = path.join(root, 'dist');
const pkg = require('../package.json');

fs.writeFileSync(
  path.join(root, 'src', 'agent-version.ts'),
  `/** Generated by scripts/build.cjs — do not edit */\nexport const AGENT_VERSION = '${pkg.version}';\n`,
);

fs.rmSync(dist, { recursive: true, force: true });
execSync('npx tsc', { cwd: root, stdio: 'inherit' });
fs.cpSync(path.join(root, 'src', 'renderer'), path.join(dist, 'renderer'), { recursive: true });
