import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  Building2,
  CreditCard,
  Layers,
  Puzzle,
  Sparkles,
  Clock,
  Receipt,
  Users,
  Rocket,
  Palette,
  Smartphone,
  MessageSquare,
  Headphones,
  Shield,
  Server,
  Key,
  Store,
  Bot,
  Handshake,
  ShieldCheck,
  Settings,
  BarChart3,
  Database,
} from "lucide-react";

export interface PlatformModuleDef {
  id: string;
  label: string;
  path: string;
  icon: LucideIcon;
  group: string;
  description: string;
  capabilities: string[];
  implemented?: boolean;
}

export const PLATFORM_MODULE_GROUPS = [
  "Overview",
  "Commercial",
  "Operations",
  "Platform",
  "Industry",
  "System",
] as const;

export const PLATFORM_MODULES: PlatformModuleDef[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    path: "/platform/dashboard",
    icon: LayoutDashboard,
    group: "Overview",
    description: "Platform-wide KPIs, revenue, health, and usage metrics.",
    capabilities: [
      "Total Companies", "Active Companies", "Trial Companies", "Expiring Companies",
      "Suspended Companies", "Total Employees", "Total Revenue", "MRR", "ARR",
      "New Signups", "Renewals Due", "Pending Payments", "Support Tickets",
      "Server Health", "Storage Usage", "API Usage",
    ],
    implemented: true,
  },
  {
    id: "companies",
    label: "Company Management",
    path: "/platform/companies",
    icon: Building2,
    group: "Commercial",
    description: "Create, manage, and monitor tenant companies.",
    capabilities: [
      "Create Company", "Edit Company", "Delete Company", "Suspend/Activate",
      "Clone Company", "Login As Admin", "Force Logout", "Reset Password",
      "Usage Statistics", "Activity Logs",
    ],
    implemented: true,
  },
  {
    id: "subscriptions",
    label: "Subscription Management",
    path: "/platform/subscriptions",
    icon: CreditCard,
    group: "Commercial",
    description: "Assign, upgrade, downgrade, and manage tenant subscriptions.",
    capabilities: [
      "Assign Plan", "Upgrade Plan", "Downgrade Plan", "Renew Subscription",
      "Cancel Subscription", "Pause Subscription", "Plan Change History",
    ],
    implemented: true,
  },
  {
    id: "plans",
    label: "Plan Builder",
    path: "/platform/plans",
    icon: Layers,
    group: "Commercial",
    description: "Design subscription plans with pricing tiers and limits.",
    capabilities: [
      "Monthly/Quarterly/Half-Yearly/Annual/Lifetime Plans",
      "Employee Limit", "Branch Limit", "Department Limit", "Storage Limit",
      "API Limit", "Admin User Limit", "Mobile User Limit",
    ],
    implemented: true,
  },
  {
    id: "modules",
    label: "Module Management",
    path: "/platform/modules",
    icon: Puzzle,
    group: "Commercial",
    description: "Enable or disable HRMS modules per subscription plan.",
    capabilities: [
      "Employee Management", "Attendance", "Leave", "Payroll", "Recruitment",
      "Training", "Performance", "Assets", "Visitors", "Helpdesk", "Expenses",
      "Travel", "Documents", "Compliance", "Exit", "Duty Roster", "Geo Tracking",
      "Patrol Tracking", "Contractors", "Clients",
    ],
    implemented: true,
  },
  {
    id: "features",
    label: "Feature Entitlements",
    path: "/platform/features",
    icon: Sparkles,
    group: "Commercial",
    description: "Control premium feature access by plan.",
    capabilities: [
      "GPS Attendance", "Face Recognition", "QR Attendance", "WhatsApp", "SMS",
      "API Access", "Custom Reports", "Workflow Builder", "Dashboard Builder",
      "Mobile App", "White Label", "SSO", "Custom Domain", "E-Signature",
    ],
    implemented: true,
  },
  {
    id: "trials",
    label: "Trial Management",
    path: "/platform/trials",
    icon: Clock,
    group: "Commercial",
    description: "Manage trial periods, extensions, and conversions.",
    capabilities: [
      "Create Trial", "Trial Duration", "Trial Extension", "Auto Expiry",
      "Conversion Tracking", "Reminder Notifications", "Auto Suspension",
    ],
    implemented: true,
  },
  {
    id: "billing",
    label: "Billing & Finance",
    path: "/platform/billing",
    icon: Receipt,
    group: "Commercial",
    description: "Invoices, payments, refunds, and revenue reporting.",
    capabilities: [
      "Subscription Invoices", "GST Invoices", "Credit Notes", "Refunds",
      "Payment History", "Renewal Tracking", "Failed Payments", "Revenue Reports",
    ],
    implemented: true,
  },
  {
    id: "crm",
    label: "CRM & Sales",
    path: "/platform/crm",
    icon: Users,
    group: "Operations",
    description: "Leads, demos, quotations, and sales pipeline.",
    capabilities: [
      "Leads", "Prospects", "Demos", "Follow Ups", "Quotations", "Proposals",
      "Sales Pipeline", "Opportunity Tracking", "Conversion Tracking",
    ],
    implemented: true,
  },
  {
    id: "onboarding",
    label: "Onboarding Center",
    path: "/platform/onboarding",
    icon: Rocket,
    group: "Operations",
    description: "Company setup wizard and bulk data migration tools.",
    capabilities: [
      "Setup Wizard", "Employee Import", "Attendance Import", "Payroll Import",
      "Bulk Migration", "Training Videos", "Knowledge Base", "Guided Setup",
    ],
    implemented: true,
  },
  {
    id: "white-label",
    label: "White Label",
    path: "/platform/white-label",
    icon: Palette,
    group: "Platform",
    description: "Branding, themes, custom domains, and mobile apps.",
    capabilities: [
      "Company Logo", "Theme", "Login Branding", "Favicon", "Email/SMS Branding",
      "Custom Domain", "Branded Mobile Apps",
    ],
    implemented: true,
  },
  {
    id: "mobile-apps",
    label: "Mobile App Management",
    path: "/platform/mobile-apps",
    icon: Smartphone,
    group: "Platform",
    description: "Control mobile apps, versions, and push notifications.",
    capabilities: [
      "Employee/Manager/HR/Attendance/Recruiter/Visitor Apps",
      "Force Update", "Version Control", "Feature Flags", "Push Notifications",
    ],
    implemented: true,
  },
  {
    id: "communications",
    label: "Communication Center",
    path: "/platform/communications",
    icon: MessageSquare,
    group: "Platform",
    description: "Email, SMS, WhatsApp templates and broadcasts.",
    capabilities: [
      "Email Templates", "SMS Templates", "WhatsApp Templates",
      "Push Notifications", "Announcements", "Broadcast Messaging",
    ],
    implemented: true,
  },
  {
    id: "support",
    label: "Support Desk",
    path: "/platform/support",
    icon: Headphones,
    group: "Operations",
    description: "Ticket management, SLA, and customer success.",
    capabilities: [
      "Ticket Management", "Live Chat", "Escalation Matrix", "SLA Management",
      "Customer Success Dashboard", "Support Analytics",
    ],
    implemented: true,
  },
  {
    id: "audit",
    label: "Audit & Security",
    path: "/platform/audit",
    icon: Shield,
    group: "Platform",
    description: "Login logs, activity tracking, and security controls.",
    capabilities: [
      "Login Logs", "Activity Logs", "Device Logs", "Failed Logins",
      "IP Restriction", "Session Management", "MFA Management",
    ],
    implemented: true,
  },
  {
    id: "infrastructure",
    label: "Server & Infrastructure",
    path: "/platform/infrastructure",
    icon: Server,
    group: "Platform",
    description: "Database, queues, backups, and disaster recovery.",
    capabilities: [
      "Database Monitoring", "Storage Monitoring", "Queue Monitoring",
      "Background Jobs", "Email/SMS/WhatsApp Queues", "Backup Management",
    ],
    implemented: true,
  },
  {
    id: "api",
    label: "API Management",
    path: "/platform/api",
    icon: Key,
    group: "Platform",
    description: "API keys, webhooks, rate limits, and integrations.",
    capabilities: [
      "API Keys", "API Usage", "Webhooks", "Third Party Integrations",
      "Rate Limits", "Access Tokens",
    ],
    implemented: true,
  },
  {
    id: "marketplace",
    label: "Marketplace",
    path: "/platform/marketplace",
    icon: Store,
    group: "Commercial",
    description: "Add-on modules and premium extensions.",
    capabilities: [
      "Payroll Add-on", "Recruitment", "Visitor Management", "GPS Tracking",
      "Patrol Tracking", "WhatsApp", "Advanced Reports", "Workflow Builder",
    ],
    implemented: true,
  },
  {
    id: "ai",
    label: "AI Control Center",
    path: "/platform/ai",
    icon: Bot,
    group: "Platform",
    description: "AI-powered HR automation and analytics.",
    capabilities: [
      "AI Chat Assistant", "AI Report Generator", "AI Payroll Verification",
      "AI Resume Screening", "AI Attendance Anomaly Detection", "AI HR Copilot",
    ],
    implemented: true,
  },
  {
    id: "partners",
    label: "Reseller & Partners",
    path: "/platform/partners",
    icon: Handshake,
    group: "Commercial",
    description: "Reseller, franchise, and partner commission management.",
    capabilities: [
      "Reseller Management", "Partner Management", "Franchise Management",
      "Commission Tracking", "White Label Partners", "Partner Dashboard",
    ],
    implemented: true,
  },
  {
    id: "security-agency",
    label: "Security Agency Modules",
    path: "/platform/security-agency",
    icon: ShieldCheck,
    group: "Industry",
    description: "Specialized modules for security agencies and facility management.",
    capabilities: [
      "Client Sites", "Deployment Management", "Guard Allocation", "Duty Roster",
      "Site Attendance", "QR Attendance", "Geo Fencing", "Patrol Monitoring",
      "Incident Reporting", "Visitor Register", "Client Billing", "Deployment Salary",
    ],
    implemented: true,
  },
  {
    id: "settings",
    label: "System Settings",
    path: "/platform/settings",
    icon: Settings,
    group: "System",
    description: "Global reference data and platform configuration.",
    capabilities: [
      "Company Categories", "Industries", "Designations", "Departments",
      "Countries", "States", "Cities", "Currency", "Time Zone", "Language",
    ],
    implemented: true,
  },
  {
    id: "analytics",
    label: "Reporting & Analytics",
    path: "/platform/analytics",
    icon: BarChart3,
    group: "System",
    description: "Revenue, churn, usage, and growth analytics.",
    capabilities: [
      "Revenue Analytics", "Customer Analytics", "Usage Analytics", "Churn Analytics",
      "Trial Conversion", "Module Usage", "Employee Growth", "Subscription Analytics",
    ],
    implemented: true,
  },
  {
    id: "tenants",
    label: "Multi-Tenant Control",
    path: "/platform/tenants",
    icon: Database,
    group: "System",
    description: "Tenant provisioning, isolation, and resource allocation.",
    capabilities: [
      "Tenant Provisioning", "Tenant Isolation", "Database Allocation",
      "Resource Allocation", "Tenant Backup", "Tenant Restore", "Migration",
    ],
    implemented: true,
  },
];

export function getPlatformModule(path: string): PlatformModuleDef | undefined {
  return PLATFORM_MODULES.find((m) => path.startsWith(m.path));
}
