#!/bin/bash
# Production-build the supervisor web UI and package debug/release APK.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ANDROID_DIR="${ROOT}/android-supervisor-app"
ASSETS_DIR="${ANDROID_DIR}/app/src/main/assets/www"
VERSION="$("$(dirname "$0")/read-android-version.sh" "${ANDROID_DIR}/app/build.gradle")"
VERSION_TS="${ROOT}/src/lib/native-app-version.ts"
API_ORIGIN="$(node "$(dirname "$0")/read-client-config.cjs" apiOrigin)"
BUILD_TYPE="${1:-debug}"

echo "==> Syncing shared client-config..."
node "$(dirname "$0")/sync-client-config.mjs"

echo "==> Syncing app version ${VERSION} into web bundle..."
cat > "$VERSION_TS" <<EOF
/** Generated by scripts/build-android-apk.sh — do not edit */
export const FIELD_TEAM_APP_VERSION = '${VERSION}';
export const OBSERVER_APP_VERSION = '1.0.6';
EOF

echo "==> Building production frontend bundle..."
cd "$ROOT"
VITE_DISABLE_PWA=true npm run build

echo "==> Syncing blocked-app package map..."
mkdir -p "${ANDROID_DIR}/app/src/main/assets"
cp "${ROOT}/shared/blocked-app-packages.json" "${ANDROID_DIR}/app/src/main/assets/blocked-app-packages.json"

echo "==> Syncing dist/ into Android assets..."
rm -rf "$ASSETS_DIR"
mkdir -p "$ASSETS_DIR"
cp -R dist/. "$ASSETS_DIR/"

echo "==> Building Android APK (${BUILD_TYPE})..."
cd "$ANDROID_DIR"

if [ -z "${JAVA_HOME:-}" ]; then
  if [ -d "/Applications/Android Studio.app/Contents/jbr/Contents/Home" ]; then
    export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
  fi
fi

GRADLE_TASK="assembleDebug"
STAMP_SUFFIX="debug"
if [ "$BUILD_TYPE" = "release" ]; then
  GRADLE_TASK="assembleRelease"
  STAMP_SUFFIX="release"
fi

./gradlew "$GRADLE_TASK" -PAPI_ORIGIN="$API_ORIGIN"

APK_DIR="${ANDROID_DIR}/app/build/outputs/apk/${STAMP_SUFFIX}"
APK_PATH="${APK_DIR}/app-${STAMP_SUFFIX}.apk"
if [ ! -f "$APK_PATH" ]; then
  APK_PATH="${APK_DIR}/app-${STAMP_SUFFIX}-unsigned.apk"
fi
if [ ! -f "$APK_PATH" ]; then
  echo "ERROR: APK not found in ${APK_DIR}" >&2
  exit 1
fi

STAMPED_APK="${ROOT}/FlexHRM-FieldTeam-v${VERSION}-${STAMP_SUFFIX}.apk"
cp "$APK_PATH" "$STAMPED_APK"

if [ "$BUILD_TYPE" = "release" ] && [[ "$APK_PATH" == *"-unsigned.apk" ]]; then
  echo ""
  echo "WARNING: Release APK is unsigned and may fail to install on device." >&2
  echo "Rebuild after configuring FLEXHRM_RELEASE_STORE_FILE or use: bash scripts/build-android-apk.sh debug" >&2
fi

echo ""
echo "APK ready:"
echo "  ${APK_PATH}"
echo "  ${STAMPED_APK}"
if [ "$BUILD_TYPE" = "debug" ]; then
  echo ""
  echo "Install: adb install -r \"${STAMPED_APK}\""
fi
